# Generated by Django 5.2 on 2026-09-20 23:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_booking_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True, verbose_name='شناسه تراکنش')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('method', models.CharField(choices=[('credit_card', 'کارت اعتباری'), ('debit_card', 'کارت نقدی'), ('paypal', 'پی\u200cپال'), ('cash', 'پرداخت در محل')], default='credit_card', max_length=20, verbose_name='روش پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('success', 'موفق'), ('failed', 'ناموفق'), ('refunded', 'بازگشت داده شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='۴ رقم آخر کارت')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking', verbose_name='رزرو')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
