# Generated by Django 5.2 on 2026-06-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
