# Generated by Django 5.2 on 2026-09-20 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
