# Generated by Django 5.2 on 2026-09-20 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
