# Generated by Django 5.2 on 2026-06-11 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام امکان')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'امکان',
                'verbose_name_plural': 'امکانات',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام اتاق')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('capacity', models.IntegerField(default=2, verbose_name='ظرفیت')),
                ('bed_type', models.CharField(max_length=100, verbose_name='نوع تخت')),
                ('size', models.IntegerField(verbose_name='مساحت (متر مربع)')),
            ],
            options={
                'verbose_name': 'نوع اتاق',
                'verbose_name_plural': 'انواع اتاق\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام هتل')),
                ('english_name', models.CharField(blank=True, max_length=200, verbose_name='نام انگلیسی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('country', models.CharField(default='ایران', max_length=100, verbose_name='کشور')),
                ('star_rating', models.IntegerField(choices=[(1, '1 ستاره'), (2, '2 ستاره'), (3, '3 ستاره'), (4, '4 ستاره'), (5, '5 ستاره')], verbose_name='ستاره')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='امتیاز')),
                ('review_count', models.IntegerField(default=0, verbose_name='تعداد نظرات')),
                ('min_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='حداقل قیمت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('website', models.URLField(blank=True, verbose_name='وبسایت')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_time', models.TimeField(default='14:00', verbose_name='ساعت تحویل اتاق')),
                ('check_out_time', models.TimeField(default='12:00', verbose_name='ساعت تخلیه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, to='hotels.amenity', verbose_name='امکانات')),
            ],
            options={
                'verbose_name': 'هتل',
                'verbose_name_plural': 'هتل\u200cها',
                'ordering': ['-rating', 'min_price'],
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/', verbose_name='تصویر')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان')),
                ('is_main', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'تصویر هتل',
                'verbose_name_plural': 'تصاویر هتل',
                'ordering': ['order', '-is_main'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='امتیاز')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان نظر')),
                ('comment', models.TextField(verbose_name='متن نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True, verbose_name='تأیید شده')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotels.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(blank=True, max_length=10, verbose_name='شماره اتاق')),
                ('price_per_night', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت هر شب')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود')),
                ('total_rooms', models.IntegerField(default=5, verbose_name='تعداد کل اتاق\u200cها')),
                ('available_rooms', models.IntegerField(default=5, verbose_name='تعداد اتاق\u200cهای موجود')),
                ('has_window', models.BooleanField(default=True, verbose_name='دارای پنجره')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='دارای بالکن')),
                ('has_kitchen', models.BooleanField(default=False, verbose_name='دارای آشپزخانه')),
                ('amenities', models.ManyToManyField(blank=True, to='hotels.amenity', verbose_name='امکانات اتاق')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.roomtype', verbose_name='نوع اتاق')),
            ],
            options={
                'verbose_name': 'اتاق',
                'verbose_name_plural': 'اتاق\u200cها',
            },
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود')),
                ('available_count', models.IntegerField(default=1, verbose_name='تعداد موجود')),
                ('special_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت ویژه')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='hotels.room')),
            ],
            options={
                'verbose_name': 'موجودی اتاق',
                'verbose_name_plural': 'موجودی اتاق\u200cها',
                'unique_together': {('room', 'date')},
            },
        ),
    ]
