# Generated by Django 5.2 on 2026-06-12 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='شرکت هواپیمایی')),
                ('code', models.CharField(max_length=10, verbose_name='کد شرکت')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='airlines/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'شرکت هواپیمایی',
                'verbose_name_plural': 'شرکت\u200cهای هواپیمایی',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام فرودگاه')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد فرودگاه')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('country', models.CharField(max_length=100, verbose_name='کشور')),
            ],
            options={
                'verbose_name': 'فرودگاه',
                'verbose_name_plural': 'فرودگاه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, verbose_name='شماره پرواز')),
                ('aircraft_type', models.CharField(blank=True, max_length=100, verbose_name='نوع هواپیما')),
                ('departure_time', models.DateTimeField(verbose_name='زمان پرواز')),
                ('arrival_time', models.DateTimeField(verbose_name='زمان arrival')),
                ('economy_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت اقتصادی')),
                ('business_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت بیزینس')),
                ('first_class_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فرست کلاس')),
                ('economy_seats', models.IntegerField(default=150, verbose_name='تعداد صندلی اقتصادی')),
                ('business_seats', models.IntegerField(default=30, verbose_name='تعداد صندلی بیزینس')),
                ('first_class_seats', models.IntegerField(default=10, verbose_name='تعداد صندلی فرست کلاس')),
                ('baggage_allowance', models.IntegerField(default=30, verbose_name='بار مجاز (کیلوگرم)')),
                ('hand_baggage', models.IntegerField(default=7, verbose_name='بار دستی (کیلوگرم)')),
                ('has_meal', models.BooleanField(default=True, verbose_name='وعده غذایی')),
                ('has_entertainment', models.BooleanField(default=True, verbose_name='سرگرمی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flights.airline')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_flights', to='flights.airport', verbose_name='مقصد')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_flights', to='flights.airport', verbose_name='مبدا')),
            ],
            options={
                'verbose_name': 'پرواز',
                'verbose_name_plural': 'پروازها',
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('class_type', models.CharField(choices=[('economy', 'اقتصادی'), ('business', 'بیزینس'), ('first', 'فرست کلاس')], default='economy', max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flights.flight')),
            ],
            options={
                'unique_together': {('flight', 'seat_number')},
            },
        ),
    ]
