# Generated by Django 5.2 on 2026-06-13 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('flight', 'Flight'), ('hotel', 'Hotel')], max_length=20)),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(max_length=20, unique=True)),
                ('session_key', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('passengers', models.TextField()),
                ('items', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=0, max_digits=12)),
                ('payment_method', models.CharField(default='credit_card', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
